In [7]:
# 多次元配列
import numpy as np

A = np.array([1, 2, 3, 4]) # 一次元配列
print(A)
print(np.ndim(A)) # np.ndim() 配列の次元数を取得
print(A.shape) # 配列の形状 結果はタプルで帰ってくる
print(A.shape[0])

[1 2 3 4]
1
(4,)
4


In [11]:
# 二次元配列
B = np.array([[1,2], [3,4], [5,6]])
print(B)
print(np.ndim(B))
print(B.shape)

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)


In [4]:
# 行列の積
import numpy as np
A = np.array([[1,2], [3,4]])
A.shape

B = np.array([[5,6], [7,8]])
B.shape
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [5]:
# 行列の積

A = np.array([[1,2,3], [4,5,6]])
A.shape

B = np.array([[1,2], [3,4], [5,6]])
B.shape
np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [8]:
# 一層ニューラルネットの実装
X = np.array([1,2])
X.shape

W = np.array([[1,3,5], [2,4,6]])
W.shape

Y = np.dot(X, W)
print(Y)

[ 5 11 17]
