In [1]:
# 3層ニューラルネットワークの実装
# ニューロン 3→3→2→2

import numpy as np

# 活性化関数の定義(非線形変換)
# シグモイド関数
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# 恒等関数(今回は実装なし.代表的な関数:分類問題→softmax関数 など)
def identity_function(x):
    return x


# -------- ↓ニューラルネット↓ -------- #

# 入力値 x1,x2
X = np.array([[1.0, 0.5]]) 

# --------- ↓入力層から第1層への信号の伝播↓ --------- #

# 重み w  
# array[0]は入力層 x1 から第1層(a1,a2,a3)にかかる重み. 
# array[1]は入力層 x2 から第1層(a1,a2,a3)にかかる重み.
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]]) 

# バイアス B
# 第1層(a1,a2,a3)に加える固定値(ニューロンの発火しやすさの調節)
B1 = np.array([0.1, 0.2, 0.3]) 

# 第1層 A1 (a1,a2,a3) の「重み付き和」(重み付き信号とバイアスの総和)
A1 = np.dot(X, W1) + B1

# 活性化関数(sigmoid)による非線形変換
Z1 = sigmoid(A1)

print(A1)
print(Z1)

# --------- ↑入力層から第1層への信号の伝播↑ --------- #

# --------- ↓第1層から第2層への信号の伝播↓ --------- #

# 重み
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
# バイアス
B2 = np.array([0.1, 0.2])

print(Z1.shape)
print(W2.shape)
print(B2.shape)

# 第2層 A2 の「重み付き和」(重み付き信号とバイアスの総和)
A2 = np.dot(Z1, W2) + B2

# 活性化関数(sigmoid)による非線形変換
Z2 = sigmoid(A2)

print(A2)
print(Z2)

# --------- ↑第1層から第2層への信号の伝播↑ --------- #

# --------- ↓第2層から出力層への信号の伝播↓ --------- #

# 重み
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
# バイアス
B3 = np.array([0.1, 0.2])

# 出力層「重み付き和」(重み付き信号とバイアスの総和)
A3 = np.dot(Z2, W3) + B3

# 恒等関数
Y = identity_function(A3)

print(A3)
print(Y)

# --------- ↑第2層から出力層への信号の伝播↑ --------- #

# -------- ↑ニューラルネット↑ -------- #


[[0.3 0.7 1.1]]
[[0.57444252 0.66818777 0.75026011]]
(1, 3)
(3, 2)
(2,)
[[0.51615984 1.21402696]]
[[0.62624937 0.7710107 ]]
[[0.31682708 0.69627909]]
[[0.31682708 0.69627909]]


In [2]:
# 上記実装のまとめ
import numpy as np

# パラメータの初期化
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]]) 
    network['b1'] = np.array([0.1, 0.2, 0.3]) 
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])

    return network


# 活性化,恒等関数の定義
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def identity_function(x):
    return x



# 入力→出力の伝播処理 = forward
def forward(network, x):
    w1, w2, w3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    a1 = np.dot(x, w1) + b1
    z1 = sigmoid(a1)
    a2 = np.dot(z1, w2) + b2
    z2 = sigmoid(a2)
    a3 = np.dot(z2, w3) + b3
    y = identity_function(a3)

    return y


network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)

print(y)

[0.31682708 0.69627909]
